services:
  # Backend Service
  fb-backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_MINI_APP_URL=${TELEGRAM_MINI_APP_URL}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@fb-db:5432/pomodoro
    ports:
      - "${BACKEND_PORT}:8000"
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    depends_on:
      - fb-db
    restart: unless-stopped

  # Frontend Service  
  fb-frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        VITE_APP_API_URL: http://localhost:${BACKEND_PORT}
    environment:
      - VITE_APP_API_URL=http://localhost:${BACKEND_PORT}
      - TELEGRAM_MINI_APP_URL=${TELEGRAM_MINI_APP_URL}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - fb-backend
    restart: unless-stopped

  fb-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pomodoro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - fb_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3032:5432"
    restart: unless-stopped

volumes:
  fb_db_data:
