services:
  postgres_test:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=budget_test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend_test:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres_test
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres_test:5432/budget_test
      - ENVIRONMENT=test
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  tests:
    build:
      context: ./
      dockerfile: tests/integration/Dockerfile
    depends_on:
      backend_test:
        condition: service_healthy
    environment:
      - API_URL=http://backend_test:8000
    volumes:
      - ./tests:/app/tests
    command: ["/app/tests/integration/run_tests.sh"]

volumes:
  postgres_data_test:
    driver: local
