services:
  fb-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://budget:budgetpwd@fb-db:5432/budgetdb
    depends_on:
      - fb-db
    ports:
      - "3030:8000"

  fb-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: builder
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - fb-backend
    ports:
      - "3031:5173"

  fb-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: budgetpwd
      POSTGRES_DB: budgetdb
    volumes:
      - fb-db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3032:5432"

volumes:
  fb-db_data:
