FROM python:3.11-slim

WORKDIR /app

# Install deps
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy source
COPY backend /app

CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
